# Generated by Django 3.1.3 on 2021-01-17 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=200, unique=True)),
                ('movie_rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_id', models.IntegerField()),
                ('comment', models.TextField()),
                ('star', models.FloatField()),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
