# Generated by Django 3.1.3 on 2021-04-11 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='relay_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.comment', verbose_name='回复对象'),
        ),
    ]
