# Generated by Django 3.1.3 on 2021-04-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210405_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='view_count',
            field=models.BigIntegerField(default=0, verbose_name='阅读数'),
        ),
    ]
